# -*- coding: utf-8 -*-
"""codsoft_task4_rock_paper_scissors.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQoYw6irhHPMtrqL8kBlL7S5pdw9NZ-X
"""

import random

choices = ["rock", "paper", "scissors"]

user_score = 0
computer_score = 0

while True:
    print("\n--- Rock Paper Scissors Game ---")
    user = input("Choose rock, paper, or scissors: ").lower()

    if user not in choices:
        print("Invalid choice! Try again.")
        continue

    computer = random.choice(choices)

    print("You chose:", user)
    print("Computer chose:", computer)

    if user == computer:
        print("Result: It's a tie ")

    elif (user == "rock" and computer == "scissors") or \
         (user == "scissors" and computer == "paper") or \
         (user == "paper" and computer == "rock"):
        print("Result: You win ")
        user_score += 1

    else:
        print("Result: You lose ")
        computer_score += 1

    print("\nScore:")
    print("You:", user_score, "| Computer:", computer_score)

    play = input("\nDo you want to play again? (yes/no): ").lower()
    if play != "yes":
        break

print("\nThanks for playing! ")
print("Final Score -> You:", user_score, "| Computer:", computer_score)