# -*- coding: utf-8 -*-
"""CODSOFT_Task3_Password_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYqcWH8K-DuaXwlhhQecErnqJ7HCntf5
"""

import random
import string

length = int(input("Enter password length: "))

characters = string.ascii_letters + string.digits + string.punctuation

password = ""

for i in range(length):
    password += random.choice(characters)

print("Generated Password:", password)