# -*- coding: utf-8 -*-
"""CODSOFT_Task1_Todo_List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mVxZqja81ELQ1XA61BSECEoBSAPlg5vL
"""

tasks = []

while True:
    print("\n1. Add Task")
    print("2. View Tasks")
    print("3. Exit")

    choice = input("Enter choice: ")

    if choice == "1":
        task = input("Enter task: ")
        tasks.append(task)
        print("Task added!")

    elif choice == "2":
        print("\nTasks:")
        for i in range(len(tasks)):
            print(i + 1, ".", tasks[i])

    elif choice == "3":
        print("Thank you!")
        break

    else:
        print("Invalid choice")